name: production

on:
  push:
    tags:
    - v*

permissions:
  contents: read
  packages: write

jobs:
  types:
    uses: potber/.github/.github/workflows/npm_types.yml@v2
    with:
      node-version-file: .nvmrc

  lint:
    uses: potber/.github/.github/workflows/npm_lint.yml@v2
    with:
      node-version-file: .nvmrc

  test:
    uses: potber/.github/.github/workflows/npm_test-coverage.yml@v2
    with:
      node-version-file: .nvmrc

  release_image:
    needs:
    - types
    - lint
    - test
    permissions:
      contents: read
      packages: write
    uses: potber/.github/.github/workflows/release_image.yml@v2
    with:
      latest: true
