name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  types:
    uses: potber/.github/.github/workflows/npm_types.yml@v2
    with:
      node-version-file: .nvmrc

  lint:
    uses: potber/.github/.github/workflows/npm_lint.yml@v2
    with:
      node-version-file: .nvmrc

  test:
    uses: potber/.github/.github/workflows/npm_test-coverage.yml@v2
    with:
      node-version-file: .nvmrc
