name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  types:
    uses: ./.github/workflows/npm_types.yml
    with:
      node-version-file: .nvmrc

  lint:
    uses: ./.github/workflows/npm_lint.yml
    with:
      node-version-file: .nvmrc

  test:
    uses: ./.github/workflows/npm_test-coverage.yml
    with:
      node-version-file: .nvmrc
